const PLANTS = [
  {
    Id: 1,
    nameOfPlant: "Snake Plant (Sansevieria)",
    water: "Low",
    temperature: "60-85°F (15-29°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 2,
    nameOfPlant: "Pothos (Epipremnum aureum)",
    water: "Moderate",
    temperature: "65-85°F (18-29°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 3,
    nameOfPlant: "Spider Plant (Chlorophytum comosum)",
    water: "Moderate",
    temperature: "55-80°F (13-27°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 4,
    nameOfPlant: "Peace Lily (Spathiphyllum)",
    water: "Moderate",
    temperature: "65-80°F (18-27°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 5,
    nameOfPlant: "ZZ Plant (Zamioculcas zamiifolia)",
    water: "Low",
    temperature: "60-75°F (15-24°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 6,
    nameOfPlant: "English Ivy (Hedera helix)",
    water: "Moderate",
    temperature: "50-75°F (10-24°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 7,
    nameOfPlant: "Rubber Plant (Ficus elastica)",
    water: "Moderate",
    temperature: "60-75°F (15-24°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 8,
    nameOfPlant: "Aloe Vera (Aloe vera)",
    water: "Low",
    temperature: "55-80°F (13-27°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 9,
    nameOfPlant: "Boston Fern (Nephrolepis exaltata)",
    water: "Moderate to high",
    temperature: "60-75°F (15-24°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 10,
    nameOfPlant: "Philodendron (Philodendron spp.)",
    water: "Moderate",
    temperature: "65-80°F (18-27°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 11,
    nameOfPlant: "Lavender (Lavandula spp.)",
    water: "Low to moderate",
    temperature: "60-75°F (15-24°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 12,
    nameOfPlant: "Rosemary (Rosmarinus officinalis)",
    water: "Low to moderate",
    temperature: "60-75°F (15-24°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 13,
    nameOfPlant: "Geranium (Pelargonium spp.)",
    water: "Moderate",
    temperature: "65-75°F (18-24°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 14,
    nameOfPlant: "Marigold (Tagetes spp.)",
    water: "Moderate",
    temperature: "60-85°F (15-29°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 15,
    nameOfPlant: "Petunia (Petunia spp.)",
    water: "Moderate",
    temperature: "60-80°F (15-27°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 16,
    nameOfPlant: "Sunflower (Helianthus annuus)",
    water: "Moderate",
    temperature: "60-75°F (15-24°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 17,
    nameOfPlant: "Pansy (Viola tricolor)",
    water: "Moderate",
    temperature: "45-65°F (7-18°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 18,
    nameOfPlant: "Zinnia (Zinnia elegans)",
    water: "Moderate",
    temperature: "70-85°F (21-29°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 19,
    nameOfPlant: "Salvia (Salvia spp.)",
    water: "Moderate",
    temperature: "65-80°F (18-27°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 20,
    nameOfPlant: "Nasturtium (Tropaeolum majus)",
    water: "Moderate",
    temperature: "60-75°F (15-24°C)",
    indoorOutdoor: "Outdoor",
  },
];
