export const Plants = [
  {
    Id: 1,
    nameOfPlant: "Snake Plant",
    water: "Low",
    temperature: "60-85°F (15-29°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 2,
    nameOfPlant: "Pothos",
    water: "Moderate",
    temperature: "65-85°F (18-29°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 3,
    nameOfPlant: "Spider Plant",
    water: "Moderate",
    temperature: "55-80°F (13-27°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 4,
    nameOfPlant: "Peace Lily",
    water: "Moderate",
    temperature: "65-80°F (18-27°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 5,
    nameOfPlant: "ZZ Plant",
    water: "Low",
    temperature: "60-75°F (15-24°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 6,
    nameOfPlant: "English Ivy",
    water: "Moderate",
    temperature: "50-75°F (10-24°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 7,
    nameOfPlant: "Rubber Plant",
    water: "Moderate",
    temperature: "60-75°F (15-24°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 8,
    nameOfPlant: "Aloe Vera",
    water: "Low",
    temperature: "55-80°F (13-27°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 9,
    nameOfPlant: "Boston Fern",
    water: "Moderate to high",
    temperature: "60-75°F (15-24°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 10,
    nameOfPlant: "Philodendron",
    water: "Moderate",
    temperature: "65-80°F (18-27°C)",
    indoorOutdoor: "Indoor",
  },
  {
    Id: 11,
    nameOfPlant: "Lavender",
    water: "Low to moderate",
    temperature: "60-75°F (15-24°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 12,
    nameOfPlant: "Rosemary",
    water: "Low to moderate",
    temperature: "60-75°F (15-24°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 13,
    nameOfPlant: "Geranium",
    water: "Moderate",
    temperature: "65-75°F (18-24°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 14,
    nameOfPlant: "Marigold",
    water: "Moderate",
    temperature: "60-85°F (15-29°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 15,
    nameOfPlant: "Petunia",
    water: "Moderate",
    temperature: "60-80°F (15-27°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 16,
    nameOfPlant: "Sunflower",
    water: "Moderate",
    temperature: "60-75°F (15-24°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 17,
    nameOfPlant: "Pansy",
    water: "Moderate",
    temperature: "45-65°F (7-18°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 18,
    nameOfPlant: "Zinnia",
    water: "Moderate",
    temperature: "70-85°F (21-29°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 19,
    nameOfPlant: "Salvia",
    water: "Moderate",
    temperature: "65-80°F (18-27°C)",
    indoorOutdoor: "Outdoor",
  },
  {
    Id: 20,
    nameOfPlant: "Nasturtium",
    water: "Moderate",
    temperature: "60-75°F (15-24°C)",
    indoorOutdoor: "Outdoor",
  },
];
